[features]
seeds = false
skip-lint = false

[programs.localnet]
ride_sharing = "G4727iEHFUyGdm1RQUbJjemQQX6K3XjTBHBhvf4CoNVL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/moon/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"


[test.validator]
url = "http://localhost:8900"

